### ISSUE TITLE
As a sports enthusiast, I would want to be able to create a profile in the Game Fitness application so I can manage my profile and history

### ISSUE THREAD

**Issue by shankarchandru** [shankarchandru/GameFitness#1]
**Title**

As a **sports enthusiast**, I need to create a profile for myself in the **Game Fitness application** so I can manage my profile and history

**Description**

The purpose of this story is to add a feature for creating a user profile in the application. The user story will be able to provide the following

- Provide an enrolling screen to input information and create an ID and password for login

-  Provide an input/update screen to add information on the progress on certain parameters that have changed since last login.

- Provide an option for the user to save the information and be able to visualize what was provided earlier

**Tasks we need to do**

- [ ] create a way for users to enter their information and make an account
- [ ] save and store user data and preexisting information
- [ ] create a visual representation for user data and track changes 

**Acceptance Criteria**

- [ ] Ability to enroll as a user in the application
- [ ] Ability to successfully save user profile information and see existing saved information
- [ ] Ability to successfully enter updated details of the original values and visualize changes (track progress)

**Story Points Estimate** - **8**

**DEV : 5
Testing : 3**

**Days to complete: 5**

**Comment by shankarchandru** [comment]
@andrw0 @urgreatman, Can you please provide an estimate?

**Comment by shankarchandru** [comment]
@shankarchandru Estimates  : 5

**Comment by andrw0** [comment]
estimate: 8

**Comment by urgreatman** [comment]
Estimates : Dev (7) , Testing (4)

**Comment by shankarchandru** [comment]
Let us go with the majority here.  Dev (5), Testing (3).
