### ISSUE TITLE
As a application designer, I need to be able to create a database design to store information related to exercises and user profiles

### ISSUE THREAD

**Issue by shankarchandru** [shankarchandru/GameFitness#2]
**Title**

As a application designer, I need to be able to create a database design to store information related to exercises and user profiles

**Description**

This work  requires to create a database design and implement a database to store information about 

- User profile Info
- User profile History Info
- Exercises and their related body parts, exercise level (difficulty)
- Exercise categories
- Game and High Stress Body parts

**Tasks we need to do**

- [ ] create a program to search the database for users 
- [ ] create a program to access the user's history 
- [ ] create a program to search for exercises based on assigned difficulty
- [ ] create a program to search for different exercises in the database
- [ ] create a program that assigns sports with various exercises 
 
**Acceptance Criteria**

- [ ] Ability to query database for user information
- [ ] Ability to query database for user history information
- [ ] Ability to query database for exercises based on difficulty level
- [ ] Ability to query database for exercises based on body parts to stretch, strengthen
- [ ] Ability to query database for maximum stress on body parts based on different game activities

**Story Point Estimates** - 11

**DEV(8)
TESTING (3)**

**Days to complete: 11**

**Comment by shankarchandru** [comment]
@andrw0 @urgreatman

**Comment by urgreatman** [comment]
Dev(5)
Testing(3)

**Comment by andrw0** [comment]
Dev(8) Testing(5)

**Comment by shankarchandru** [comment]
My Estimates : Dev(8), Testing(3)

**Comment by shankarchandru** [comment]
@andrw0 , @urgreatman , I am thinking, we should vote for higher time for dev work here as the database table design is very important for a good application querying.  Let us stick with 8 for Dev work and probably 3 days as Abdul suggested for testing.
