### ISSUE TITLE
Provide a personalized list of exercises for a specific user profile based on inputs

### ISSUE THREAD

**Issue by shankarchandru** [shankarchandru/GameFitness#3]
**Title** 

As as application designer, I need to build application logic to define the set of exercises based on user input (height, weight, game/activity, BMI etc.), so I can provide a personalized list of exercises

**Description**

This work will support the following 

- Add the ability to  build a logic to personalize a list of exercises based on their inputs (BMI and other preferences like swimming etc..)
- Add the ability to make these functions available to be called by the UI to get a list of exercises
- Add the ability to update the list based on user choices

**Tasks we need to do**
- [ ] design a program to choose exercises based of the inputs from the user
- [ ] build a program to assign and save information of the list of exercises to the user
- [ ] build a program to save the different exercise choices by the user and record any changes the user might make

**Acceptance Criteria**

- [ ] Provide a personalized list of exercises based on inputs for a user as a pick list
- [ ] Save information on the chosen list of exercises for the user
- [ ] Update history information as inputs change for the user along with the list of exercises that were performed.

**Story Points - 

DEV ()
TESTING ()**

**Comment by shankarchandru** [comment]
@andrw0 @urgreatman, can you please provide estimates

**Comment by andrw0** [comment]
Dev(8)
Testing(5)

**Comment by shankarchandru** [comment]
Dev(5)
Testing(5)

**Comment by shankarchandru** [comment]
@urgreatman, What do you think?

**Comment by urgreatman** [comment]
Dev(5)
Testing (5)
