### ISSUE TITLE
Collect a list of exercises for different games and difficulty level. 

### ISSUE THREAD

**Issue by shankarchandru** [shankarchandru/GameFitness#4]
**Title** 
As an application designer, I need to collect all different exercises specific to games along with their difficulty level, so can have a document that can be used to input values in my data store. 

**Description**

The purpose of this story is to collect a list of exercises for each games, body parts (lower back, forearms etc. )

**Tasks that need to be done**

- [ ] decide which sports to include in the program
- [ ] look up common injuries for each sport
- [ ] collect exercises for each sport 
- [ ] input the collected exercises into a database that will be used with the program

**Acceptance Criteria**

- [ ] Create a document/PDF with a list of exercises for each body part and supported game activity

**Story Points - 8**

**Days to complete: 7**

**Comment by shankarchandru** [comment]
@andrw0 @urgreatman, Can you please provide your estimates here?

**Comment by urgreatman** [comment]
Dev(5)
Testing(3)

**Comment by shankarchandru** [comment]
Estimates : 8

**Comment by andrw0** [comment]
5

**Comment by shankarchandru** [comment]
Let us go with majority here :-)
